# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7885c6f1f5cda5e72b753ca2b28e8e05beabebd0772ed620e2a8c039b94d73abba3d7a3d25684347f38f586371e9197a159804d465b8fafdc589f4f51367fb9

test:
  secret_key_base: deebd80954e135ce9bb188f3da995715a16d2928e6ecc2a01af978e4c080787a65234fe1779a90d71dc5e7dbca3ac5f07482940e92a61a497eb17f546897adfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
